version: '3.8'

services:
  postcode-scraper:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: postcode-scraper-app
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    networks:
      - app-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: postcode-scraper-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - postcode-scraper
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - with-nginx

  # Optional: Add monitoring with Watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: postcode-scraper-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    restart: unless-stopped
    profiles:
      - with-monitoring

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
  app-logs:
